version: '3'

services:
  postgres:
    image: postgres
    restart: on-failure
    volumes:
    - postgres_data
    environment:
      POSTGRES_DB: db_keycloak
      POSTGRES_USER: user_keycloak
      POSTGRES_PASSWORD: password_keycloak

  keycloak:
    image: jboss/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: db_keycloak
      DB_USER: user_keycloak
      DB_PASSWORD: password_keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - postgres

  nginx:
    network_mode: host
    image: nginx:stable-alpine
    restart: on-failure
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8888:8888
      - 4200:4200

volumes:
  postgres_data:
    driver: local
